version: "3.5"

networks:
  hydronet:
    name: demo_hydronet
    internal: true
    ipam:
      config:
        - subnet: 172.16.0.0/24

  extnet:
    driver: bridge

volumes:
  sonardata:

services:


  rootcause-worker:
    build: .
    container_name: rootcause-worker
    command: celery -A app.celery worker
    depends_on:
      - mongodb
    networks:
      - hydronet

  rootcause:
    build: .
    container_name: rootcause
    command: python app.py
    depends_on:
      - mongodb
      - rootcause-worker
    ports:
      - "5000:5000"
    networks:
      - hydronet
      - extnet


  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - hydronet
    environment:
      - "POSTGRES_DB=docker"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"

  gateway:
    image:  hydrosphere/serving-gateway:8634cd7dc2d555625ec570478c29dc06ebe4d419
    container_name: gateway
    ports:
      - "29090:9090"
      - "29091:9091"
    networks:
      - hydronet
    environment:
      - "API_GATEWAY_HOST=managerui"
      - "API_GATEWAY_GRPC_PORT=9090"
      - "API_GATEWAY_HTTP_PORT=80"
      - "HTTP_PORT=9090"
      - "GRPC_PORT=9091"
      - "APP_OPTS=-Dapplication.reqstore.enabled=true -Dapplication.reqstore.host=reqstore -Dapplication.reqstore.port=9091"

  manager:
    image:  hydrosphere/serving-manager:fe83c6ae3a0fe87883aadd9d1250766c4766645c
    container_name: manager
    ports:
      - "19090:9090"
      - "19091:9091"
    networks:
      - hydronet
      - extnet
    environment:
      - "DATABASE_HOST=postgres"
      - "NETWORK_NAME=demo_hydronet"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  managerui:
    image:  hydrosphere/serving-manager-ui:dd4dc9470662da22153ad5484503b531d55ea9e9--661756209
    container_name: managerui
    depends_on:
      - manager
      - gateway
      - reqstore
      - serving-sonar
      - timemachine
      - rootcause
    ports:
      - "80:80"
      - "9090:9090"
    networks:
      - extnet
      - hydronet
    environment:
      - "MANAGER_HOST=manager"
      - "MANAGER_HTTP_PORT=9090"
      - "MANAGER_GRPC_PORT=9091"
      - "GATEWAY_HOST=gateway"
      - "GATEWAY_HTTP_PORT=9090"
      - "GATEWAY_GRPC_PORT=9091"
      - "MONITORING_HOST=serving-sonar"
      - "MONITORING_HTTP_PORT=9090"
      - "MONITORING_GRPC_PORT=9091"
      - "REQSTORE_HOST=reqstore"
      - "REQSTORE_HTTP_PORT=9090"
      - "REQSTORE_GRPC_PORT=9091"
      - "TIMEMACHINE_HOST=timemachine"
      - "TIMEMACHINE_HTTP_PORT=9090"
      - "TIMEMACHINE_GRPC_PORT=9091"
      - "ROOTCAUSE_HOST=rootcause"
      - "ROOTCAUSE_HTTP_PORT=5000"

  influxdb:
    image: influxdb:1.5.2
    container_name: influxdb
    ports:
      - "8086:8086"
    restart: always
    networks:
      - hydronet
      - extnet

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - extnet
      - hydronet
  sonar-data:
    image: docker.hydrosphere.io/sonar-data:latest
    volumes:
      - sonardata:/data

  serving-sonar:
    image:  docker.hydrosphere.io/sonar:783acd53df216d88d31c6ea927160547ce539aba
    container_name: serving-sonar
    depends_on:
      - postgres
    ports:
      - "39090:9090"
      - "39091:9091"
    environment:
      - "DB_TYPE=postgres"
      - "DB_JDBC_URL=jdbc:postgresql://postgres:5432/docker"
      - "DB_USER=docker"
      - "DB_PASS=docker"
      - "INFLUX_HOST=influxdb"
      - "INFLUX_PORT=8086"
      - "MONGO_HOST=mongodb"
      - "HTTP_PORT=9090"
      - "GRPC_PORT=9091"
      - "SIDECAR_HOST=managerui"
      - "SIDECAR_HTTP_PORT=80"
      - "SIDECAR_GRPC_PORT=9090"
    networks:
      - extnet
      - hydronet
    volumes:
      - sonardata:/data

  reqstore:
    image: hydrosphere/reqstore_cpp:0.0.12
    container_name: reqstore
    environment:
      - "AWS_DEFAULT_REGION=us-west-2"
      - "AWS_SECRET_ACCESS_KEY=none"
      - "AWS_ACCESS_KEY_ID=none"
      - "DB_NAME=default"
      - "BACKUP_PROVIDER=none"
      - "DST_LOCAL_DIR=default"
      - "DST_BUCKET=default"
      - "SRC_LOCAL_DIR=default"
      - "HTTP_PORT=9090"
      - "GRPC_PORT=9091"
      - "DEBUG=1"
    ports:
      - "7265:9090"
      - "7266:9091"
    networks:
      - hydronet
      - extnet
    volumes:
      - sonardata:/default

  timemachine:
    image:  docker.hydrosphere.io/hydro-serving-timemachine:0.0.4
    container_name: timemachine
    environment:
      - "HTTP_PORT=9090"
      - "REQSTORE_HOST=reqstore"
      - "REQSTORE_PORT=9091"
      - "PREDICTION_HOST=gateway"
      - "PREDICTION_PORT=9091"
      - "MANAGER_PORT=9091"
    ports:
      - "7366:9090"
    networks:
      - hydronet
      - extnet

