# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drift.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='drift.proto',
  package='userpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x64rift.proto\x12\x06userpb\"\x0e\n\x0cHelloRequest\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x13\n\x11\x44\x65ployInfoRequest\"~\n\x12\x44\x65ployInfoResponse\x12\x18\n\x10\x61vailable_routes\x18\x01 \x03(\t\x12\x18\n\x10gitCurrentBranch\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x15\n\rpythonVersion\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\"a\n\x0eMetricsRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\x05\x12\x10\n\x08training\x18\x03 \x01(\t\x12\x12\n\ndeployment\x18\x04 \x01(\t\"\xab\x01\n\x04Test\x12(\n\x0e\x66inal_decision\x18\x01 \x01(\x0e\x32\x10.userpb.decision\x12#\n\x0btest_status\x18\x02 \x01(\x0e\x32\x0e.userpb.status\x12#\n\tdecisions\x18\x03 \x03(\x0e\x32\x10.userpb.decision\x12\x0f\n\x07metrics\x18\x04 \x03(\x02\x12\x10\n\x08p_values\x18\x05 \x03(\x02\x12\x0c\n\x04name\x18\x06 \x01(\t\"X\n\x0fMetricsResponse\x12\x1b\n\x05tests\x18\x01 \x03(\x0b\x32\x0c.userpb.Test\x12(\n\x0e\x66inal_decision\x18\x02 \x01(\x0e\x32\x10.userpb.decision*9\n\x08\x64\x65\x63ision\x12\x16\n\x12THERE_IS_NO_CHANGE\x10\x00\x12\x15\n\x11THERE_IS_A_CHANGE\x10\x01*#\n\x06status\x12\n\n\x06\x46\x41ILED\x10\x00\x12\r\n\tSUCCEEDED\x10\x01\x32\xd3\x01\n\x14\x44riftDetectorService\x12\x36\n\x05hello\x12\x14.userpb.HelloRequest\x1a\x15.userpb.HelloResponse\"\x00\x12\x45\n\ndeployInfo\x12\x19.userpb.DeployInfoRequest\x1a\x1a.userpb.DeployInfoResponse\"\x00\x12<\n\x07metrics\x12\x16.userpb.MetricsRequest\x1a\x17.userpb.MetricsResponse\"\x00\x62\x06proto3')
)

_DECISION = _descriptor.EnumDescriptor(
  name='decision',
  full_name='userpb.decision',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='THERE_IS_NO_CHANGE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THERE_IS_A_CHANGE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=585,
  serialized_end=642,
)
_sym_db.RegisterEnumDescriptor(_DECISION)

decision = enum_type_wrapper.EnumTypeWrapper(_DECISION)
_STATUS = _descriptor.EnumDescriptor(
  name='status',
  full_name='userpb.status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCEEDED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=644,
  serialized_end=679,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
THERE_IS_NO_CHANGE = 0
THERE_IS_A_CHANGE = 1
FAILED = 0
SUCCEEDED = 1



_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='userpb.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=37,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='userpb.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='userpb.HelloResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=71,
)


_DEPLOYINFOREQUEST = _descriptor.Descriptor(
  name='DeployInfoRequest',
  full_name='userpb.DeployInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=92,
)


_DEPLOYINFORESPONSE = _descriptor.Descriptor(
  name='DeployInfoResponse',
  full_name='userpb.DeployInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='available_routes', full_name='userpb.DeployInfoResponse.available_routes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gitCurrentBranch', full_name='userpb.DeployInfoResponse.gitCurrentBranch', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='userpb.DeployInfoResponse.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pythonVersion', full_name='userpb.DeployInfoResponse.pythonVersion', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='userpb.DeployInfoResponse.version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=220,
)


_METRICSREQUEST = _descriptor.Descriptor(
  name='MetricsRequest',
  full_name='userpb.MetricsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='userpb.MetricsRequest.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_version', full_name='userpb.MetricsRequest.model_version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='training', full_name='userpb.MetricsRequest.training', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deployment', full_name='userpb.MetricsRequest.deployment', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=319,
)


_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='userpb.Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='final_decision', full_name='userpb.Test.final_decision', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_status', full_name='userpb.Test.test_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decisions', full_name='userpb.Test.decisions', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='userpb.Test.metrics', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='p_values', full_name='userpb.Test.p_values', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='userpb.Test.name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=493,
)


_METRICSRESPONSE = _descriptor.Descriptor(
  name='MetricsResponse',
  full_name='userpb.MetricsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tests', full_name='userpb.MetricsResponse.tests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='final_decision', full_name='userpb.MetricsResponse.final_decision', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=583,
)

_TEST.fields_by_name['final_decision'].enum_type = _DECISION
_TEST.fields_by_name['test_status'].enum_type = _STATUS
_TEST.fields_by_name['decisions'].enum_type = _DECISION
_METRICSRESPONSE.fields_by_name['tests'].message_type = _TEST
_METRICSRESPONSE.fields_by_name['final_decision'].enum_type = _DECISION
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE
DESCRIPTOR.message_types_by_name['DeployInfoRequest'] = _DEPLOYINFOREQUEST
DESCRIPTOR.message_types_by_name['DeployInfoResponse'] = _DEPLOYINFORESPONSE
DESCRIPTOR.message_types_by_name['MetricsRequest'] = _METRICSREQUEST
DESCRIPTOR.message_types_by_name['Test'] = _TEST
DESCRIPTOR.message_types_by_name['MetricsResponse'] = _METRICSRESPONSE
DESCRIPTOR.enum_types_by_name['decision'] = _DECISION
DESCRIPTOR.enum_types_by_name['status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'drift_pb2'
  # @@protoc_insertion_point(class_scope:userpb.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESPONSE,
  '__module__' : 'drift_pb2'
  # @@protoc_insertion_point(class_scope:userpb.HelloResponse)
  })
_sym_db.RegisterMessage(HelloResponse)

DeployInfoRequest = _reflection.GeneratedProtocolMessageType('DeployInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _DEPLOYINFOREQUEST,
  '__module__' : 'drift_pb2'
  # @@protoc_insertion_point(class_scope:userpb.DeployInfoRequest)
  })
_sym_db.RegisterMessage(DeployInfoRequest)

DeployInfoResponse = _reflection.GeneratedProtocolMessageType('DeployInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _DEPLOYINFORESPONSE,
  '__module__' : 'drift_pb2'
  # @@protoc_insertion_point(class_scope:userpb.DeployInfoResponse)
  })
_sym_db.RegisterMessage(DeployInfoResponse)

MetricsRequest = _reflection.GeneratedProtocolMessageType('MetricsRequest', (_message.Message,), {
  'DESCRIPTOR' : _METRICSREQUEST,
  '__module__' : 'drift_pb2'
  # @@protoc_insertion_point(class_scope:userpb.MetricsRequest)
  })
_sym_db.RegisterMessage(MetricsRequest)

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), {
  'DESCRIPTOR' : _TEST,
  '__module__' : 'drift_pb2'
  # @@protoc_insertion_point(class_scope:userpb.Test)
  })
_sym_db.RegisterMessage(Test)

MetricsResponse = _reflection.GeneratedProtocolMessageType('MetricsResponse', (_message.Message,), {
  'DESCRIPTOR' : _METRICSRESPONSE,
  '__module__' : 'drift_pb2'
  # @@protoc_insertion_point(class_scope:userpb.MetricsResponse)
  })
_sym_db.RegisterMessage(MetricsResponse)



_DRIFTDETECTORSERVICE = _descriptor.ServiceDescriptor(
  name='DriftDetectorService',
  full_name='userpb.DriftDetectorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=682,
  serialized_end=893,
  methods=[
  _descriptor.MethodDescriptor(
    name='hello',
    full_name='userpb.DriftDetectorService.hello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deployInfo',
    full_name='userpb.DriftDetectorService.deployInfo',
    index=1,
    containing_service=None,
    input_type=_DEPLOYINFOREQUEST,
    output_type=_DEPLOYINFORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='metrics',
    full_name='userpb.DriftDetectorService.metrics',
    index=2,
    containing_service=None,
    input_type=_METRICSREQUEST,
    output_type=_METRICSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DRIFTDETECTORSERVICE)

DESCRIPTOR.services_by_name['DriftDetectorService'] = _DRIFTDETECTORSERVICE

# @@protoc_insertion_point(module_scope)
